name: Web App
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Install dependencies
        run: dart run build_runner build -d
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
          customArgs: --target="lib/main_production.dart"
