name: Web App
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: moksh-tehlan/flutter-web-pages/mokshtehlan-gh-pages.yaml@v7
